version: '2'
services:
  gl_coopcycle-app:
    image: gl_coopcycle
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://gl_coopcycle-postgresql:5432/GL_Coopcycle
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  gl_coopcycle-postgresql:
    extends:
      file: postgresql.yml
      service: gl_coopcycle-postgresql
